version: '3.6'
services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file: .env.local
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  graphql-engine:
    image: hasura/graphql-engine:v1.3.3
    ports:
      - '6063:8080'
    depends_on:
      - 'postgres'
    restart: always
    env_file: .env.local
volumes:
  db_data:
