version: "3.6"
services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
  graphql-engine:
    image: hasura/graphql-engine:v1.0.0
    ports:
      - "6060:8080"
    depends_on:
      - "postgres"
    restart: always
    env_file: .env.local
volumes:
  db_data:
